#!/bin/bash
# 🔧 Script para prueba de DETECCIÓN DE CRISIS
# Este script muestra cómo testear la detección de crisis directamente

echo "════════════════════════════════════════════════════════════════"
echo "  GUÍA DE PRUEBA: DETECCIÓN DE MENSAJES DE CRISIS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. ABRE LA APLICACIÓN EN EL NAVEGADOR"
echo "   URL: http://localhost:5173/ (o tu URL de staging)"
echo ""
echo "2. ABRE LA CONSOLA DEL NAVEGADOR"
echo "   Atajo: F12 → Tab 'Console'"
echo ""
echo "3. INGRESA A LA SECCIÓN DE AGENTE (Agent.tsx)"
echo "   • Completa la autenticación"
echo "   • Verás el chat con Gero"
echo ""
echo "4. ESCRIBE UNO DE ESTOS MENSAJES (COPIAR Y PEGAR):"
echo ""
echo "═══ PRUEBAS DE RIESGO EXTREMO ═══════════════════════════════════"
echo ""
echo "  Test 1 - Ideación suicida básica:"
echo "    → 'me quiero suicidar'"
echo "    Respuesta esperada: EXTREME RISK DETECTED"
echo ""
echo "  Test 2 - Intento futuro:"
echo "    → 'voy a suicidarme'"
echo "    Respuesta esperada: EXTREME RISK DETECTED"
echo ""
echo "  Test 3 - Desespero total:"
echo "    → 'no puedo más, no aguanto esto'"
echo "    Respuesta esperada: EXTREME RISK DETECTED"
echo ""
echo "  Test 4 - Vida sin sentido:"
echo "    → 'mejor si no estuviera aquí'"
echo "    Respuesta esperada: EXTREME RISK DETECTED"
echo ""
echo "═══ PRUEBAS DE RIESGO ALTO ══════════════════════════════════════"
echo ""
echo "  Test 5 - Depresión severa:"
echo "    → 'estoy muy deprimido, todo es sin sentido'"
echo "    Respuesta esperada: HIGH RISK DETECTED"
echo ""
echo "  Test 6 - Ansiedad extrema:"
echo "    → 'tengo ansiedad severa, no puedo respirar'"
echo "    Respuesta esperada: HIGH RISK DETECTED"
echo ""
echo "  Test 7 - Soledad extrema:"
echo "    → 'nadie me quiere, estoy completamente solo'"
echo "    Respuesta esperada: HIGH RISK DETECTED"
echo ""
echo "  Test 8 - Sin esperanza:"
echo "    → 'no tengo esperanza, no veo salida'"
echo "    Respuesta esperada: HIGH RISK DETECTED"
echo ""
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "5. VERIFICA EN LA CONSOLA DEL NAVEGADOR"
echo ""
echo "   Deberías ver un mensaje como:"
echo ""
echo "   ✓ [CRISIS DETECTION] 🚨 EXTREME RISK DETECTED: ['suicidarme'] in: 'me quiero suicidar'"
echo "   ✓ [CRISIS DETECTION] ⚠️ HIGH RISK DETECTED: ['deprimido'] in: '...'"
echo ""
echo "6. VERIFICA EL FLUJO"
echo ""
echo "   ✓ El agente responde con mensaje de contención"
echo "   ✓ Se marca como 'crisis_detected'"
echo "   ✓ Se envía al backend para guardar en base de datos"
echo ""
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "📊 PALABRAS CLAVE DISPONIBLES"
echo ""
echo "RIESGO EXTREMO (31 palabras):"
echo "  suicidio, suicidarme, me quiero suicidar, voy a suicidarme,"
echo "  matarme, quitarme la vida, no quiero vivir, desesperación,"
echo "  autolesión, cortarme, lastimarme, ya no puedo, no puedo más,"
echo "  cansado/a de vivir, mejor si no estuviera, mejor muerto,"
echo "  sin razón para vivir, sin motivo para vivir, vida sin sentido,"
echo "  deseo de morir, quiero desaparecer, quiero irme, acabar con todo"
echo ""
echo "RIESGO ALTO (43 palabras):"
echo "  depresión, deprimido/a, muy deprimido, ansiedad severa,"
echo "  ansiedad extrema, pánico, ataque de pánico, ataques de pánico,"
echo "  quiero morir, todo es sin sentido, nada tiene sentido,"
echo "  soy un fracaso, soy inútil, soy basura, no sirvo para nada,"
echo "  no merezco vivir, nadie me quiere, nadie me ama, estoy solo/a,"
echo "  me duele mucho, es insoportable, no aguanto esta vida,"
echo "  no puedo con esto, todo me afecta mucho, he fracasado,"
echo "  he perdido todo, no tengo esperanza, sin esperanza, sin futuro,"
echo "  insoportable, no veo salida, sin salida, quiero escapar,"
echo "  quiero huir"
echo ""
echo "═════════════════════════════════════════════════════════════════"
echo ""
echo "✅ VALIDACIÓN"
echo ""
echo "Para confirmar que todo funciona:"
echo ""
echo "1. Frontend:"
echo "   ✓ Consola muestra [CRISIS DETECTION]"
echo "   ✓ Agent responde con contención"
echo ""
echo "2. Backend:"
echo "   ✓ POST /wp-json/gero/v1/guardar-conversation-state → 200"
echo "   ✓ Base de datos: byw_agente_retencion"
echo "   ✓ Campo: prioridad_caso = 'alto'"
echo "   ✓ Campo: justificacion = '[CRISIS EXTREMA] ...'"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
